#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

# need to GET the main page to trigger the autoconfig of the ownCloud instance
pushd $OPENSHIFT_REPO_DIR/php
php index.php
popd

